all:
  vars:
    ansible_ssh_private_key_file: /vagrant/keys/ansible.key
    ansible_user: ansible
  children:
    k8s:
      hosts:
        k8s1:
        k8s2:
        k8s3:

k8s_master:
  hosts:
    k8s1:
k8s_workers:
  hosts:
    k8s2:
    k8s3: